
// Generated by Cadence Genus(TM) Synthesis Solution 19.13-s073_1
// Generated on: Aug  1 2020 22:55:16 +07 (Aug  1 2020 15:55:16 UTC)

// Verification Directory fv/Bound_Flasher 

module Bound_Flasher(clk, reset, flick, LED);
  input clk, reset, flick;
  output [15:0] LED;
  wire clk, reset, flick;
  wire [15:0] LED;
  wire [15:0] next_LED;
  wire [2:0] next_index;
  wire [2:0] current_index;
  wire [1:0] next_state;
  wire [1:0] current_state;
  wire \LED[4]_707 , \LED[5]_708 , UNCONNECTED, UNCONNECTED0,
       UNCONNECTED1, UNCONNECTED2, UNCONNECTED3, UNCONNECTED4;
  wire UNCONNECTED5, UNCONNECTED6, UNCONNECTED7, UNCONNECTED8,
       UNCONNECTED9, UNCONNECTED10, UNCONNECTED11, UNCONNECTED12;
  wire UNCONNECTED13, UNCONNECTED14, UNCONNECTED15, UNCONNECTED16,
       UNCONNECTED17, UNCONNECTED18, UNCONNECTED19, n_1;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  wire n_13, n_14, n_15, n_16, n_18, n_19, n_20, n_21;
  wire n_22, n_23, n_24, n_25, n_26, n_27, n_28, n_29;
  wire n_31, n_32, n_33, n_34, n_35, n_37, n_38, n_42;
  wire n_43, n_44, n_45, n_46, n_47, n_48, n_49, n_51;
  wire n_52, n_53, n_54, n_56, n_59, n_60, n_61, n_62;
  wire n_63, n_64, n_67, n_68, n_70, n_71, n_72, n_73;
  wire n_75, n_77, n_78, n_79, n_80, n_81, n_82, n_83;
  wire n_84, n_85, n_86, n_87, n_88, n_90, n_93, n_94;
  wire n_95, n_96, n_98, n_99, n_101, n_102, n_103, n_105;
  wire n_106, n_107, n_108, n_109, n_110, n_111, n_112, n_113;
  wire n_114, n_115, n_116, n_117, n_118, n_119, n_121, n_122;
  wire n_123, n_124, n_125, n_126, n_127, n_128, n_130, n_131;
  wire n_133, n_137, n_142, n_145, n_146, n_150, n_151, n_153;
  wire n_163, n_168, n_169, n_191, n_194, n_195, n_196, n_197;
  wire n_198, n_199, n_200, n_201, n_202, n_210, n_216, n_217;
  wire n_218, n_219, n_220, n_221;
  DFFRHQX4 \LED_reg[4] (.RN (n_133), .CK (clk), .D (n_131), .Q
       (\LED[4]_707 ));
  DFFRHQX4 \LED_reg[5] (.RN (n_133), .CK (clk), .D (n_130), .Q
       (\LED[5]_708 ));
  SDFFRHQX8 \LED_reg[13] (.RN (n_133), .CK (clk), .D (LED[13]), .SI
       (next_LED[13]), .SE (n_191), .Q (LED[13]));
  SDFFRHQX8 \LED_reg[14] (.RN (n_133), .CK (clk), .D (n_168), .SI
       (next_LED[14]), .SE (n_191), .Q (LED[14]));
  SDFFRHQX8 \LED_reg[1] (.RN (n_133), .CK (clk), .D (n_145), .SI
       (next_LED[1]), .SE (n_191), .Q (LED[1]));
  SDFFRHQX8 \LED_reg[12] (.RN (n_133), .CK (clk), .D (LED[12]), .SI
       (next_LED[12]), .SE (n_191), .Q (LED[12]));
  SDFFRHQX8 \LED_reg[3] (.RN (n_133), .CK (clk), .D (LED[3]), .SI
       (next_LED[3]), .SE (n_191), .Q (LED[3]));
  SDFFRHQX8 \LED_reg[2] (.RN (n_133), .CK (clk), .D (LED[2]), .SI
       (next_LED[2]), .SE (n_191), .Q (LED[2]));
  SDFFRHQX8 \LED_reg[8] (.RN (n_133), .CK (clk), .D (LED[8]), .SI
       (next_LED[8]), .SE (n_191), .Q (LED[8]));
  SDFFRHQX8 \LED_reg[6] (.RN (n_133), .CK (clk), .D (LED[6]), .SI
       (next_LED[6]), .SE (n_191), .Q (LED[6]));
  SDFFRHQX8 \LED_reg[9] (.RN (n_133), .CK (clk), .D (LED[9]), .SI
       (next_LED[9]), .SE (n_191), .Q (LED[9]));
  SDFFRHQX8 \LED_reg[10] (.RN (n_133), .CK (clk), .D (LED[10]), .SI
       (next_LED[10]), .SE (n_191), .Q (LED[10]));
  SDFFRHQX8 \LED_reg[11] (.RN (n_133), .CK (clk), .D (LED[11]), .SI
       (next_LED[11]), .SE (n_191), .Q (LED[11]));
  SDFFRHQX8 \LED_reg[7] (.RN (n_133), .CK (clk), .D (LED[7]), .SI
       (next_LED[7]), .SE (n_191), .Q (LED[7]));
  SDFFRHQX8 \LED_reg[0] (.RN (n_133), .CK (clk), .D (LED[0]), .SI
       (next_LED[0]), .SE (n_191), .Q (LED[0]));
  OAI21X2 g5358__2398(.A0 (next_LED[4]), .A1 (n_202), .B0 (n_78), .Y
       (n_131));
  OAI21X2 g5359__5107(.A0 (next_LED[5]), .A1 (n_202), .B0 (n_77), .Y
       (n_130));
  DFFSRHQX4 \current_index_reg[0] (.RN (n_82), .SN (n_98), .CK (clk),
       .D (next_index[0]), .Q (current_index[0]));
  DFFSRHQX8 \current_index_reg[1] (.RN (n_86), .SN (n_96), .CK (clk),
       .D (next_index[1]), .Q (current_index[1]));
  DFFRHQX4 \LED_reg[15] (.RN (n_133), .CK (clk), .D (n_127), .Q
       (LED[15]));
  DFFSRHQX8 \current_index_reg[2] (.RN (n_85), .SN (n_93), .CK (clk),
       .D (next_index[2]), .Q (current_index[2]));
  TLATNXL \next_LED_reg[12] (.GN (n_128), .D (n_112), .Q
       (next_LED[12]), .QN (UNCONNECTED));
  TLATNXL \next_LED_reg[13] (.GN (n_128), .D (n_119), .Q
       (next_LED[13]), .QN (UNCONNECTED0));
  TLATNXL \next_LED_reg[14] (.GN (n_128), .D (n_121), .Q
       (next_LED[14]), .QN (UNCONNECTED1));
  TLATNXL \next_LED_reg[1] (.GN (n_128), .D (n_106), .Q (next_LED[1]),
       .QN (UNCONNECTED2));
  TLATNXL \next_index_reg[1] (.GN (n_128), .D (n_110), .Q
       (next_index[1]), .QN (UNCONNECTED3));
  TLATNXL \next_LED_reg[2] (.GN (n_128), .D (n_115), .Q (next_LED[2]),
       .QN (UNCONNECTED4));
  TLATNXL \next_index_reg[2] (.GN (n_128), .D (n_107), .Q
       (next_index[2]), .QN (UNCONNECTED5));
  TLATNXL \next_LED_reg[3] (.GN (n_128), .D (n_116), .Q (next_LED[3]),
       .QN (UNCONNECTED6));
  TLATNXL \next_LED_reg[4] (.GN (n_128), .D (n_125), .Q (UNCONNECTED7),
       .QN (next_LED[4]));
  OAI21X2 g5373__6260(.A0 (next_LED[15]), .A1 (n_202), .B0 (n_80), .Y
       (n_127));
  TLATNXL \next_LED_reg[7] (.GN (n_128), .D (n_117), .Q (next_LED[7]),
       .QN (UNCONNECTED8));
  TLATNXL \next_LED_reg[8] (.GN (n_128), .D (n_126), .Q (next_LED[8]),
       .QN (UNCONNECTED9));
  TLATNXL \next_LED_reg[6] (.GN (n_128), .D (n_118), .Q (next_LED[6]),
       .QN (UNCONNECTED10));
  TLATNXL \next_LED_reg[9] (.GN (n_128), .D (n_105), .Q (next_LED[9]),
       .QN (UNCONNECTED11));
  TLATNXL \next_LED_reg[10] (.GN (n_128), .D (n_114), .Q
       (next_LED[10]), .QN (UNCONNECTED12));
  TLATNXL \next_LED_reg[11] (.GN (n_128), .D (n_113), .Q
       (next_LED[11]), .QN (UNCONNECTED13));
  TLATNXL \next_index_reg[0] (.GN (n_128), .D (n_111), .Q
       (next_index[0]), .QN (UNCONNECTED14));
  TLATNXL \next_LED_reg[5] (.GN (n_128), .D (n_122), .Q
       (UNCONNECTED15), .QN (next_LED[5]));
  TLATNXL \next_LED_reg[0] (.GN (n_128), .D (n_216), .Q (next_LED[0]),
       .QN (UNCONNECTED16));
  AO22X1 g5385__4319(.A0 (LED[7]), .A1 (n_124), .B0 (LED[9]), .B1
       (n_210), .Y (n_126));
  AO22X1 g5397__8428(.A0 (LED[3]), .A1 (n_124), .B0 (LED[5]), .B1
       (n_123), .Y (n_125));
  AO22X1 g5398__5526(.A0 (LED[4]), .A1 (n_124), .B0 (LED[6]), .B1
       (n_123), .Y (n_122));
  AO22X1 g5399__6783(.A0 (LED[13]), .A1 (n_124), .B0 (LED[15]), .B1
       (n_210), .Y (n_121));
  AO22X1 g5382__1617(.A0 (LED[12]), .A1 (n_124), .B0 (n_168), .B1
       (n_210), .Y (n_119));
  AO22X1 g5383__2802(.A0 (LED[5]), .A1 (n_124), .B0 (LED[7]), .B1
       (n_123), .Y (n_118));
  AO22X1 g5384__1705(.A0 (LED[6]), .A1 (n_124), .B0 (LED[8]), .B1
       (n_210), .Y (n_117));
  AO22X1 g5396__5122(.A0 (LED[2]), .A1 (n_124), .B0 (LED[4]), .B1
       (n_123), .Y (n_116));
  AO22X1 g5395__8246(.A0 (n_145), .A1 (n_124), .B0 (LED[3]), .B1
       (n_210), .Y (n_115));
  AO22X1 g5387__7098(.A0 (LED[9]), .A1 (n_124), .B0 (LED[11]), .B1
       (n_123), .Y (n_114));
  AO22X1 g5388__6131(.A0 (LED[10]), .A1 (n_124), .B0 (LED[12]), .B1
       (n_210), .Y (n_113));
  AO22X1 g5389__1881(.A0 (LED[11]), .A1 (n_124), .B0 (LED[13]), .B1
       (n_123), .Y (n_112));
  MX2X1 g5391__5115(.A (n_108), .B (n_109), .S0 (current_index[0]), .Y
       (n_111));
  AO22X1 g5392__7482(.A0 (current_index[1]), .A1 (n_109), .B0 (n_95),
       .B1 (n_108), .Y (n_110));
  AO22X1 g5393__4733(.A0 (current_index[2]), .A1 (n_109), .B0 (n_45),
       .B1 (n_108), .Y (n_107));
  AO22X1 g5394__6161(.A0 (LED[0]), .A1 (n_124), .B0 (LED[2]), .B1
       (n_210), .Y (n_106));
  AO22X1 g5386__9315(.A0 (LED[8]), .A1 (n_124), .B0 (LED[10]), .B1
       (n_210), .Y (n_105));
  TLATNXL \next_LED_reg[15] (.GN (n_128), .D (n_103), .Q
       (UNCONNECTED17), .QN (next_LED[15]));
  DFFRHQX4 \current_state_reg[1] (.RN (n_81), .CK (clk), .D
       (next_state[1]), .Q (current_state[1]));
  DFFSRHQX8 \current_state_reg[0] (.RN (reset), .SN (n_220), .CK (clk),
       .D (next_state[0]), .Q (current_state[0]));
  TLATNXL \next_state_reg[0] (.GN (n_128), .D (n_102), .Q
       (next_state[0]), .QN (UNCONNECTED18));
  TLATNXL \next_state_reg[1] (.GN (n_128), .D (n_210), .Q
       (next_state[1]), .QN (UNCONNECTED19));
  AND2X1 g5407__9945(.A (n_168), .B (n_102), .Y (n_103));
  NOR2XL g5408__2883(.A (n_101), .B (n_108), .Y (n_109));
  NOR2X1 g5409__2346(.A (n_101), .B (n_123), .Y (n_124));
  OAI21XL g5411__1666(.A0 (n_13), .A1 (n_88), .B0 (n_217), .Y (n_102));
  NAND2XL g5410__7410(.A (n_99), .B (n_217), .Y (n_108));
  OAI21X1 g5412__6417(.A0 (n_142), .A1 (n_218), .B0 (n_99), .Y (n_123));
  NAND2BXL g5419__5477(.AN (current_index[0]), .B (n_94), .Y (n_98));
  NAND2BXL g5416__2398(.AN (n_95), .B (n_94), .Y (n_96));
  NAND2BXL g5418__5107(.AN (n_84), .B (n_94), .Y (n_93));
  OAI31X1 g5413__6260(.A0 (n_142), .A1 (n_150), .A2 (n_79), .B0 (n_90),
       .Y (n_101));
  NAND3BXL g5414__4319(.AN (n_13), .B (current_state[0]), .C (n_87), .Y
       (n_99));
  NOR2BX1 g5422__8428(.AN (n_90), .B (n_220), .Y (n_94));
  NAND2BXL g5415__5526(.AN (n_87), .B (current_state[0]), .Y (n_88));
  AOI21XL g5421__6783(.A0 (n_95), .A1 (n_202), .B0 (n_83), .Y (n_86));
  AOI21XL g5424__3680(.A0 (n_84), .A1 (n_202), .B0 (n_83), .Y (n_85));
  AOI21XL g5425__1617(.A0 (current_index[0]), .A1 (n_202), .B0 (n_83),
       .Y (n_82));
  AND2XL g5428__2802(.A (reset), .B (n_191), .Y (n_81));
  NAND2X4 g5427__1705(.A (LED[15]), .B (n_200), .Y (n_80));
  NAND2X4 g5429__8246(.A (LED[4]), .B (n_200), .Y (n_78));
  NAND2X4 g5430__7098(.A (LED[5]), .B (n_200), .Y (n_77));
  NOR4X1 g5420__1881(.A (n_19), .B (n_21), .C (n_72), .D (n_75), .Y
       (n_87));
  INVXL g5423(.A (n_218), .Y (n_79));
  NAND4XL g5431__7482(.A (n_60), .B (n_52), .C (n_64), .D (n_70), .Y
       (n_75));
  NOR2X6 g5440__6161(.A (n_56), .B (n_68), .Y (n_73));
  OAI221X1 g5437__9315(.A0 (n_1), .A1 (n_62), .B0 (LED[9]), .B1 (n_4),
       .C0 (n_61), .Y (n_72));
  OAI221X1 g5438__9945(.A0 (n_219), .A1 (n_48), .B0 (LED[2]), .B1
       (n_146), .C0 (n_67), .Y (n_71));
  AOI221X1 g5435__2883(.A0 (LED[7]), .A1 (n_63), .B0 (LED[5]), .B1
       (n_137), .C0 (n_20), .Y (n_70));
  NAND3X6 g5447__2346(.A (n_38), .B (n_54), .C (flick), .Y (n_68));
  AOI22XL g5439__1666(.A0 (n_219), .A1 (n_221), .B0 (LED[0]), .B1
       (n_146), .Y (n_67));
  AOI22XL g5441__7410(.A0 (LED[9]), .A1 (n_63), .B0 (n_169), .B1
       (n_62), .Y (n_64));
  MX2X1 g5442__6417(.A (n_63), .B (LED[10]), .S0 (LED[8]), .Y (n_61));
  MX2X1 g5443__5477(.A (n_63), .B (LED[7]), .S0 (LED[6]), .Y (n_60));
  INVXL g5449(.A (n_83), .Y (n_133));
  NOR2X8 g5459__2398(.A (n_34), .B (n_151), .Y (n_59));
  NAND2XL g5455__5107(.A (reset), .B (n_195), .Y (n_83));
  CLKAND2X6 g5453__6260(.A (n_16), .B (n_53), .Y (n_54));
  AOI211XL g5460__4319(.A0 (LED[3]), .A1 (n_153), .B0 (n_51), .C0
       (n_24), .Y (n_52));
  AO21X1 g5456__8428(.A0 (n_13), .A1 (n_142), .B0 (n_194), .Y (n_128));
  NOR2X8 g5452__5526(.A (n_142), .B (n_22), .Y (n_49));
  NOR2XL g5451__6783(.A (LED[3]), .B (n_46), .Y (n_48));
  NOR2X4 g5450__3680(.A (LED[0]), .B (n_46), .Y (n_47));
  XNOR2X1 g5457__1617(.A (current_index[2]), .B (n_15), .Y (n_45));
  NOR2XL g5454__2802(.A (n_37), .B (n_62), .Y (n_63));
  NOR2X4 g5461__1705(.A (n_23), .B (n_43), .Y (n_44));
  NOR2X6 g5462__5122(.A (n_33), .B (n_32), .Y (n_42));
  AOI21XL g5463__7098(.A0 (current_index[2]), .A1 (current_index[1]),
       .B0 (n_62), .Y (n_84));
  OR2X1 g5472__6131(.A (n_29), .B (n_37), .Y (n_95));
  INVXL g5483(.A (n_35), .Y (n_90));
  NAND2X8 g5481__5115(.A (current_index[0]), .B (n_14), .Y (n_53));
  NAND2X4 g5467__7482(.A (n_27), .B (n_26), .Y (n_34));
  NAND2X4 g5465__6161(.A (n_25), .B (n_31), .Y (n_32));
  CLKAND2X2 g5468__9315(.A (n_28), .B (n_27), .Y (n_38));
  NAND2X4 g5470__2883(.A (n_25), .B (n_26), .Y (n_43));
  NOR3XL g5482__2346(.A (current_index[1]), .B (current_index[2]), .C
       (current_index[0]), .Y (n_62));
  MXI2XL g5474__1666(.A (n_146), .B (LED[2]), .S0 (LED[0]), .Y (n_24));
  NAND2X4 g5477__7410(.A (n_10), .B (n_9), .Y (n_23));
  MX2X1 g5475__6417(.A (LED[11]), .B (n_18), .S0 (LED[15]), .Y (n_21));
  MX2X1 g5476__5477(.A (n_146), .B (LED[4]), .S0 (current_index[0]), .Y
       (n_20));
  OAI22XL g5478__2398(.A0 (LED[12]), .A1 (n_18), .B0 (LED[11]), .B1
       (n_169), .Y (n_19));
  NOR2X4 g5491__5107(.A (current_state[0]), .B (n_13), .Y (n_35));
  NAND2XL g5501__6260(.A (current_index[0]), .B (current_index[1]), .Y
       (n_15));
  NOR2X8 g5485__4319(.A (current_index[1]), .B (n_163), .Y (n_14));
  NOR2X6 g5492__8428(.A (n_5), .B (current_state[0]), .Y (n_16));
  NOR2BX1 g5498__5526(.AN (current_index[1]), .B (current_index[0]), .Y
       (n_37));
  NOR2BX1 g5499__6783(.AN (current_index[0]), .B (current_index[1]), .Y
       (n_29));
  AND2X1 g5489__3680(.A (LED[2]), .B (n_10), .Y (n_51));
  NOR2X4 g5495__1617(.A (LED[2]), .B (LED[1]), .Y (n_9));
  CLKAND2X6 g5486__2802(.A (LED[3]), .B (LED[2]), .Y (n_8));
  CLKAND2X6 g5496__1705(.A (LED[1]), .B (LED[0]), .Y (n_7));
  NOR2X6 g5488__5122(.A (LED[11]), .B (LED[10]), .Y (n_28));
  NOR2X8 g5503__8246(.A (LED[6]), .B (LED[7]), .Y (n_31));
  NOR2X2 g5497__7098(.A (\LED[4]_707 ), .B (\LED[5]_708 ), .Y (n_6));
  CLKAND2X6 g5500__6131(.A (\LED[4]_707 ), .B (\LED[5]_708 ), .Y
       (n_11));
  INVX2 g5505(.A (n_5), .Y (n_13));
  NOR2X6 g5490__1881(.A (LED[8]), .B (LED[9]), .Y (n_27));
  NOR2X8 g5487__5115(.A (LED[13]), .B (LED[15]), .Y (n_26));
  NOR2X6 g5502__7482(.A (LED[14]), .B (LED[12]), .Y (n_25));
  INVXL g5515(.A (LED[10]), .Y (n_4));
  INVXL g5508(.A (LED[13]), .Y (n_18));
  CLKINVX4 g5506(.A (current_state[1]), .Y (n_5));
  INVX2 g5512(.A (LED[3]), .Y (n_10));
  INVXL g5517(.A (LED[12]), .Y (n_1));
  NAND2X8 g5568__9315(.A (n_7), .B (n_8), .Y (n_22));
  NAND2X6 g5574__9945(.A (n_47), .B (n_44), .Y (n_56));
  CLKINVX6 fopt5579(.A (n_16), .Y (n_142));
  CLKINVX8 fopt5584(.A (n_53), .Y (n_151));
  CLKINVX6 fopt5596(.A (current_index[2]), .Y (n_163));
  CLKINVX20 fopt5617(.A (n_199), .Y (n_191));
  NAND2X6 g5586__5621(.A (n_35), .B (flick), .Y (n_195));
  OAI22X4 g5436__5623(.A0 (n_196), .A1 (n_197), .B0 (n_194), .B1
       (n_195), .Y (n_198));
  NAND2X8 g5566__5624(.A (flick), .B (n_49), .Y (n_196));
  NAND2X8 g5564__5625(.A (n_59), .B (n_42), .Y (n_197));
  BUFX6 g5626(.A (n_198), .Y (n_200));
  OR2X4 g5607__5627(.A (n_73), .B (n_201), .Y (n_202));
  OAI22X4 g5436__4733_dup(.A0 (n_196), .A1 (n_197), .B0 (n_194), .B1
       (n_195), .Y (n_201));
  BUFX2 drc_buf_sp5634(.A (n_123), .Y (n_210));
  AO21X1 g2(.A0 (n_145), .A1 (n_123), .B0 (n_124), .Y (n_216));
  NOR4BX1 g5641(.AN (n_38), .B (n_51), .C (n_43), .D (n_71), .Y
       (n_218));
  BUFX2 fopt5645(.A (\LED[5]_708 ), .Y (LED[5]));
  BUFX2 fopt5647(.A (\LED[4]_707 ), .Y (LED[4]));
  INVX3 g5649(.A (reset), .Y (n_194));
  BUFX2 fopt5651(.A (LED[14]), .Y (n_168));
  BUFX2 fopt5653(.A (LED[1]), .Y (n_145));
  NAND2X4 g5480__5655(.A (n_6), .B (n_31), .Y (n_46));
  NAND2X4 g5466__5657(.A (n_28), .B (n_11), .Y (n_33));
  NOR2BX1 g5659(.AN (n_29), .B (current_index[2]), .Y (n_219));
  INVX1 fopt5661(.A (LED[5]), .Y (n_153));
  INVX1 fopt5663(.A (LED[4]), .Y (n_137));
  INVX1 fopt5665(.A (n_151), .Y (n_150));
  OR2X6 g5434_0_0__5667(.A (n_73), .B (n_198), .Y (n_199));
  NAND2BX1 g5669(.AN (n_79), .B (n_54), .Y (n_217));
  NAND2BX1 g5671(.AN (n_191), .B (reset), .Y (n_220));
  NAND3X1 g5672(.A (n_11), .B (LED[0]), .C (n_31), .Y (n_221));
  INVX2 fopt5674(.A (n_145), .Y (n_146));
  INVX2 fopt5676(.A (n_168), .Y (n_169));
endmodule

