
// Generated by Cadence Genus(TM) Synthesis Solution 19.13-s073_1
// Generated on: Aug  3 2020 23:08:34 +07 (Aug  3 2020 16:08:34 UTC)

// Verification Directory fv/Bound_Flasher 

module Bound_Flasher(clk, reset, flick, LED);
  input clk, reset, flick;
  output [15:0] LED;
  wire clk, reset, flick;
  wire [15:0] LED;
  wire [15:0] next_LED;
  wire [2:0] next_index;
  wire [2:0] current_index;
  wire [1:0] next_state;
  wire [1:0] current_state;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, UNCONNECTED18,
       UNCONNECTED19, n_0, n_1, n_2;
  wire n_3, n_4, n_5, n_6, n_7, n_8, n_9, n_10;
  wire n_11, n_12, n_13, n_14, n_15, n_16, n_18, n_19;
  wire n_21, n_22, n_23, n_24, n_25, n_26, n_28, n_29;
  wire n_30, n_31, n_32, n_33, n_34, n_35, n_36, n_38;
  wire n_39, n_40, n_41, n_42, n_43, n_45, n_46, n_47;
  wire n_48, n_50, n_51, n_52, n_54, n_55, n_56, n_57;
  wire n_58, n_59, n_60, n_62, n_63, n_64, n_65, n_66;
  wire n_68, n_69, n_70, n_71, n_73, n_74, n_75, n_76;
  wire n_77, n_78, n_79, n_81, n_82, n_83, n_84, n_85;
  wire n_86, n_87, n_88, n_89, n_90, n_91, n_92, n_93;
  wire n_94, n_95, n_97, n_98, n_99, n_100, n_101, n_102;
  wire n_103, n_104, n_105, n_106, n_108, n_109, n_110, n_111;
  wire n_112, n_113, n_114, n_115, n_116, n_117, n_118, n_119;
  wire n_120, n_121, n_122, n_123, n_128, n_133, n_167, n_183;
  wire n_214, n_215, n_216, n_217, n_219, n_220;
  DFFRHQX4 \LED_reg[6] (.RN (n_123), .CK (clk), .D (n_121), .Q
       (LED[6]));
  SDFFRHQX8 \LED_reg[14] (.RN (n_123), .CK (clk), .D (next_LED[14]),
       .SI (LED[14]), .SE (n_122), .Q (LED[14]));
  SDFFRHQX8 \LED_reg[4] (.RN (n_123), .CK (clk), .D (next_LED[4]), .SI
       (LED[4]), .SE (n_122), .Q (LED[4]));
  SDFFRHQX8 \LED_reg[12] (.RN (n_123), .CK (clk), .D (next_LED[12]),
       .SI (LED[12]), .SE (n_122), .Q (LED[12]));
  SDFFRHQX8 \LED_reg[13] (.RN (n_123), .CK (clk), .D (next_LED[13]),
       .SI (LED[13]), .SE (n_122), .Q (LED[13]));
  SDFFRHQX8 \LED_reg[11] (.RN (n_123), .CK (clk), .D (next_LED[11]),
       .SI (LED[11]), .SE (n_122), .Q (LED[11]));
  SDFFRHQX8 \LED_reg[3] (.RN (n_123), .CK (clk), .D (next_LED[3]), .SI
       (LED[3]), .SE (n_122), .Q (LED[3]));
  SDFFRHQX8 \LED_reg[2] (.RN (n_123), .CK (clk), .D (next_LED[2]), .SI
       (LED[2]), .SE (n_122), .Q (LED[2]));
  SDFFRHQX8 \LED_reg[8] (.RN (n_123), .CK (clk), .D (next_LED[8]), .SI
       (LED[8]), .SE (n_122), .Q (LED[8]));
  SDFFRHQX8 \LED_reg[7] (.RN (n_123), .CK (clk), .D (next_LED[7]), .SI
       (LED[7]), .SE (n_122), .Q (LED[7]));
  SDFFRHQX8 \LED_reg[0] (.RN (n_123), .CK (clk), .D (next_LED[0]), .SI
       (LED[0]), .SE (n_122), .Q (LED[0]));
  SDFFRHQX8 \LED_reg[9] (.RN (n_123), .CK (clk), .D (next_LED[9]), .SI
       (LED[9]), .SE (n_122), .Q (LED[9]));
  SDFFRHQX8 \LED_reg[10] (.RN (n_123), .CK (clk), .D (next_LED[10]),
       .SI (LED[10]), .SE (n_122), .Q (LED[10]));
  SDFFRHQX8 \LED_reg[5] (.RN (n_123), .CK (clk), .D (next_LED[5]), .SI
       (LED[5]), .SE (n_122), .Q (LED[5]));
  SDFFRHQX8 \LED_reg[1] (.RN (n_123), .CK (clk), .D (next_LED[1]), .SI
       (LED[1]), .SE (n_122), .Q (LED[1]));
  DFFSRHQX8 \current_index_reg[1] (.RN (n_83), .SN (n_93), .CK (clk),
       .D (next_index[1]), .Q (current_index[1]));
  DFFSRHQX4 \current_index_reg[0] (.RN (n_79), .SN (n_91), .CK (clk),
       .D (next_index[0]), .Q (current_index[0]));
  OAI21X2 g5414__2398(.A0 (next_LED[6]), .A1 (n_122), .B0 (n_74), .Y
       (n_121));
  DFFRHQX4 \LED_reg[15] (.RN (n_123), .CK (clk), .D (n_119), .Q
       (LED[15]));
  DFFSRHQX8 \current_index_reg[2] (.RN (n_82), .SN (n_89), .CK (clk),
       .D (next_index[2]), .Q (current_index[2]));
  TLATNXL \next_index_reg[1] (.GN (n_120), .D (n_118), .Q
       (next_index[1]), .QN (UNCONNECTED));
  TLATNXL \next_index_reg[2] (.GN (n_120), .D (n_114), .Q
       (next_index[2]), .QN (UNCONNECTED0));
  OAI21X2 g5428__5107(.A0 (next_LED[15]), .A1 (n_122), .B0 (n_75), .Y
       (n_119));
  TLATNXL \next_index_reg[0] (.GN (n_120), .D (n_117), .Q
       (next_index[0]), .QN (UNCONNECTED1));
  TLATNXL \next_LED_reg[12] (.GN (n_120), .D (n_100), .Q
       (next_LED[12]), .QN (UNCONNECTED2));
  TLATNXL \next_LED_reg[14] (.GN (n_120), .D (n_106), .Q
       (next_LED[14]), .QN (UNCONNECTED3));
  TLATNXL \next_LED_reg[13] (.GN (n_120), .D (n_99), .Q (next_LED[13]),
       .QN (UNCONNECTED4));
  TLATNXL \next_LED_reg[1] (.GN (n_120), .D (n_98), .Q (next_LED[1]),
       .QN (UNCONNECTED5));
  TLATNXL \next_LED_reg[2] (.GN (n_120), .D (n_105), .Q (next_LED[2]),
       .QN (UNCONNECTED6));
  TLATNXL \next_LED_reg[3] (.GN (n_120), .D (n_108), .Q (next_LED[3]),
       .QN (UNCONNECTED7));
  TLATNXL \next_LED_reg[4] (.GN (n_120), .D (n_113), .Q (next_LED[4]),
       .QN (UNCONNECTED8));
  TLATNXL \next_LED_reg[10] (.GN (n_120), .D (n_102), .Q
       (next_LED[10]), .QN (UNCONNECTED9));
  TLATNXL \next_LED_reg[6] (.GN (n_120), .D (n_109), .Q
       (UNCONNECTED10), .QN (next_LED[6]));
  TLATNXL \next_LED_reg[8] (.GN (n_120), .D (n_104), .Q (next_LED[8]),
       .QN (UNCONNECTED11));
  TLATNXL \next_LED_reg[9] (.GN (n_120), .D (n_103), .Q (next_LED[9]),
       .QN (UNCONNECTED12));
  TLATNXL \next_LED_reg[7] (.GN (n_120), .D (n_97), .Q (next_LED[7]),
       .QN (UNCONNECTED13));
  TLATNXL \next_LED_reg[11] (.GN (n_120), .D (n_101), .Q
       (next_LED[11]), .QN (UNCONNECTED14));
  TLATNXL \next_LED_reg[5] (.GN (n_120), .D (n_112), .Q (next_LED[5]),
       .QN (UNCONNECTED15));
  TLATNXL \next_LED_reg[0] (.GN (n_120), .D (n_214), .Q (next_LED[0]),
       .QN (UNCONNECTED16));
  AO22X1 g5454__6260(.A0 (current_index[1]), .A1 (n_115), .B0 (n_92),
       .B1 (n_116), .Y (n_118));
  MX2X1 g5446__4319(.A (n_116), .B (n_115), .S0 (current_index[0]), .Y
       (n_117));
  AO22X1 g5447__8428(.A0 (current_index[2]), .A1 (n_115), .B0 (n_38),
       .B1 (n_116), .Y (n_114));
  TLATNXL \next_LED_reg[15] (.GN (n_120), .D (n_95), .Q
       (UNCONNECTED17), .QN (next_LED[15]));
  AO22X1 g5451__5526(.A0 (LED[3]), .A1 (n_111), .B0 (LED[5]), .B1
       (n_183), .Y (n_113));
  AO22X1 g5452__6783(.A0 (LED[4]), .A1 (n_111), .B0 (LED[6]), .B1
       (n_110), .Y (n_112));
  AO22X1 g5453__3680(.A0 (LED[5]), .A1 (n_111), .B0 (LED[7]), .B1
       (n_110), .Y (n_109));
  AO22X1 g5450__1617(.A0 (LED[2]), .A1 (n_111), .B0 (LED[4]), .B1
       (n_183), .Y (n_108));
  AO22X1 g5437__1705(.A0 (LED[13]), .A1 (n_111), .B0 (LED[15]), .B1
       (n_183), .Y (n_106));
  DFFSRHQX8 \current_state_reg[0] (.RN (reset), .SN (n_86), .CK (clk),
       .D (next_state[0]), .Q (current_state[0]));
  AO22X1 g5449__5122(.A0 (LED[1]), .A1 (n_111), .B0 (LED[3]), .B1
       (n_110), .Y (n_105));
  AO22X1 g5439__8246(.A0 (LED[7]), .A1 (n_111), .B0 (LED[9]), .B1
       (n_183), .Y (n_104));
  AO22X1 g5440__7098(.A0 (LED[8]), .A1 (n_111), .B0 (LED[10]), .B1
       (n_110), .Y (n_103));
  AO22X1 g5441__6131(.A0 (LED[9]), .A1 (n_111), .B0 (LED[11]), .B1
       (n_183), .Y (n_102));
  AO22X1 g5442__1881(.A0 (LED[10]), .A1 (n_111), .B0 (LED[12]), .B1
       (n_110), .Y (n_101));
  AO22X1 g5443__5115(.A0 (LED[11]), .A1 (n_111), .B0 (LED[13]), .B1
       (n_183), .Y (n_100));
  AO22X1 g5444__7482(.A0 (LED[12]), .A1 (n_111), .B0 (LED[14]), .B1
       (n_110), .Y (n_99));
  AO22X1 g5448__4733(.A0 (LED[0]), .A1 (n_111), .B0 (LED[2]), .B1
       (n_183), .Y (n_98));
  AO22X1 g5438__6161(.A0 (LED[6]), .A1 (n_111), .B0 (LED[8]), .B1
       (n_183), .Y (n_97));
  DFFRHQX4 \current_state_reg[1] (.RN (n_78), .CK (clk), .D
       (next_state[1]), .Q (current_state[1]));
  TLATNXL \next_state_reg[0] (.GN (n_120), .D (n_94), .Q
       (next_state[0]), .QN (UNCONNECTED18));
  AND2X1 g5462__9315(.A (LED[14]), .B (n_94), .Y (n_95));
  NAND2BXL g5471__9945(.AN (n_92), .B (n_90), .Y (n_93));
  NAND2BXL g5470__2883(.AN (current_index[0]), .B (n_90), .Y (n_91));
  NAND2BXL g5472__2346(.AN (n_81), .B (n_90), .Y (n_89));
  NOR2XL g5463__1666(.A (n_88), .B (n_116), .Y (n_115));
  TLATNXL \next_state_reg[1] (.GN (n_120), .D (n_183), .Q
       (next_state[1]), .QN (UNCONNECTED19));
  NOR2X1 g5464__7410(.A (n_88), .B (n_110), .Y (n_111));
  NAND2XL g5465__6417(.A (n_84), .B (n_87), .Y (n_116));
  OAI31X1 g5466__5477(.A0 (current_state[1]), .A1 (n_14), .A2 (n_73),
       .B0 (n_87), .Y (n_94));
  NOR2BX1 g5476__2398(.AN (n_85), .B (n_86), .Y (n_90));
  OAI21XL g5469__5107(.A0 (n_76), .A1 (n_77), .B0 (n_85), .Y (n_88));
  AOI21XL g5477__4319(.A0 (n_92), .A1 (n_167), .B0 (n_215), .Y (n_83));
  AOI21XL g5478__8428(.A0 (n_81), .A1 (n_167), .B0 (n_215), .Y (n_82));
  AOI21XL g5479__5526(.A0 (current_index[0]), .A1 (n_167), .B0 (n_215),
       .Y (n_79));
  NOR2BX1 g5480__6783(.AN (reset), .B (n_167), .Y (n_78));
  NAND2BXL g5474__3680(.AN (n_77), .B (n_76), .Y (n_87));
  NAND2X4 g5481__1617(.A (LED[15]), .B (n_122), .Y (n_75));
  NAND2X4 g5482__2802(.A (LED[6]), .B (n_122), .Y (n_74));
  NAND2XL g5485__1705(.A (n_167), .B (reset), .Y (n_86));
  NAND3BXL g5468__5122(.AN (current_state[1]), .B (current_state[0]),
       .C (n_73), .Y (n_84));
  NAND2BXL g5475__8246(.AN (n_216), .B (n_71), .Y (n_77));
  CLKINVX20 g5486(.A (n_70), .Y (n_122));
  NOR2X8 g5487__7098(.A (n_69), .B (n_220), .Y (n_70));
  NOR4X1 g5473__6131(.A (n_31), .B (n_22), .C (n_64), .D (n_68), .Y
       (n_73));
  NAND2X8 g5489__5115(.A (n_42), .B (n_66), .Y (n_69));
  NAND4XL g5483__7482(.A (n_58), .B (n_45), .C (n_51), .D (n_56), .Y
       (n_68));
  NAND2X8 g5492__6161(.A (n_59), .B (n_55), .Y (n_66));
  AOI221X1 g5493__9315(.A0 (LED[3]), .A1 (n_217), .B0 (LED[2]), .B1
       (n_50), .C0 (n_54), .Y (n_65));
  OAI221X1 g5488__9945(.A0 (LED[9]), .A1 (n_57), .B0 (LED[10]), .B1
       (n_46), .C0 (n_47), .Y (n_64));
  NAND3X8 g5491__2883(.A (n_62), .B (flick), .C (n_52), .Y (n_63));
  NOR2X6 g5500__1666(.A (n_48), .B (n_43), .Y (n_59));
  AOI22XL g5494__7410(.A0 (LED[10]), .A1 (n_57), .B0 (n_30), .B1
       (n_35), .Y (n_58));
  MX2X1 g5495__6417(.A (LED[7]), .B (n_128), .S0 (n_57), .Y (n_56));
  CLKAND2X6 g5496__5477(.A (flick), .B (n_41), .Y (n_55));
  OAI222XL g5498__2398(.A0 (LED[0]), .A1 (n_217), .B0 (LED[2]), .B1
       (n_26), .C0 (LED[1]), .C1 (n_133), .Y (n_54));
  INVXL g5501(.A (n_215), .Y (n_123));
  NOR2X6 g5510__5107(.A (n_10), .B (n_32), .Y (n_52));
  AOI221X1 g5511__6260(.A0 (LED[0]), .A1 (current_index[0]), .B0
       (LED[5]), .B1 (n_50), .C0 (n_28), .Y (n_51));
  NAND2X4 g5502__5526(.A (n_40), .B (n_76), .Y (n_48));
  AOI22XL g5499__6783(.A0 (LED[13]), .A1 (n_23), .B0 (LED[9]), .B1
       (n_46), .Y (n_47));
  AOI211XL g5512__3680(.A0 (LED[7]), .A1 (n_128), .B0 (n_19), .C0
       (n_29), .Y (n_45));
  NAND2X1 g5515__1617(.A (n_34), .B (reset), .Y (n_120));
  NAND2X6 g5504__2802(.A (n_39), .B (n_25), .Y (n_43));
  NOR3X8 g5513__1705(.A (n_12), .B (n_18), .C (n_33), .Y (n_41));
  CLKAND2X6 g5506__5122(.A (n_40), .B (n_39), .Y (n_62));
  XNOR2X1 g5509__8246(.A (current_index[2]), .B (n_9), .Y (n_38));
  AOI21XL g5514__7098(.A0 (current_index[2]), .A1 (current_index[1]),
       .B0 (n_35), .Y (n_81));
  NOR2XL g5507__6131(.A (n_24), .B (n_35), .Y (n_57));
  NAND2XL g5518__1881(.A (n_33), .B (current_state[1]), .Y (n_34));
  NAND2X6 g5528__5115(.A (n_5), .B (n_13), .Y (n_32));
  NAND2X6 g5523__4733(.A (current_index[0]), .B (n_15), .Y (n_76));
  OAI22XL g5526__6161(.A0 (LED[13]), .A1 (n_21), .B0 (LED[11]), .B1
       (n_30), .Y (n_31));
  OAI22XL g5525__9315(.A0 (LED[5]), .A1 (current_index[0]), .B0
       (LED[2]), .B1 (n_0), .Y (n_29));
  MX2X1 g5530__9945(.A (n_133), .B (LED[2]), .S0 (n_26), .Y (n_28));
  CLKAND2X6 g5527__2883(.A (n_3), .B (n_6), .Y (n_25));
  CLKAND2X6 g5519__2346(.A (n_11), .B (flick), .Y (n_36));
  OR2X1 g5522__1666(.A (n_16), .B (n_24), .Y (n_92));
  INVXL g5517(.A (n_35), .Y (n_23));
  MX2X1 g5529__7410(.A (LED[11]), .B (n_21), .S0 (LED[15]), .Y (n_22));
  CLKAND2X6 g5531__6417(.A (n_2), .B (n_8), .Y (n_40));
  INVXL g5535(.A (n_33), .Y (n_71));
  NOR2X4 g5521__5477(.A (LED[6]), .B (n_18), .Y (n_60));
  CLKAND2X6 g5532__2398(.A (n_7), .B (n_4), .Y (n_39));
  NOR2X6 g5538__5107(.A (current_index[1]), .B (n_1), .Y (n_15));
  NAND2X6 g5544__6260(.A (current_state[1]), .B (n_14), .Y (n_33));
  NOR3XL g5524__4319(.A (current_index[1]), .B (current_index[2]), .C
       (current_index[0]), .Y (n_35));
  NOR2X6 g5552__8428(.A (n_133), .B (current_state[0]), .Y (n_13));
  NAND2X8 g5550__5526(.A (n_50), .B (n_128), .Y (n_12));
  NOR2XL g5541__6783(.A (LED[3]), .B (n_50), .Y (n_19));
  INVXL g5534(.A (n_11), .Y (n_85));
  NAND2XL g5540__1617(.A (current_index[0]), .B (current_index[1]), .Y
       (n_9));
  NOR2X4 g5536__2802(.A (LED[14]), .B (LED[13]), .Y (n_8));
  NOR2X6 g5549__1705(.A (LED[11]), .B (LED[10]), .Y (n_7));
  OR2X6 g5554__5122(.A (LED[7]), .B (LED[5]), .Y (n_18));
  NOR2BX1 g5553__8246(.AN (current_index[0]), .B (current_index[1]), .Y
       (n_16));
  NOR2X4 g5537__7098(.A (LED[2]), .B (LED[1]), .Y (n_6));
  CLKAND2X6 g5546__6131(.A (current_state[1]), .B (LED[1]), .Y (n_5));
  NOR2X4 g5551__1881(.A (LED[8]), .B (LED[9]), .Y (n_4));
  NOR2X4 g5547__5115(.A (LED[3]), .B (LED[0]), .Y (n_3));
  NOR2X6 g5539__7482(.A (LED[12]), .B (LED[15]), .Y (n_2));
  NOR2X2 g5543__4733(.A (current_state[1]), .B (current_state[0]), .Y
       (n_11));
  NOR2BX1 g5542__6161(.AN (current_index[1]), .B (current_index[0]), .Y
       (n_24));
  CLKINVX4 g5557(.A (current_index[2]), .Y (n_1));
  INVXL g5556(.A (LED[14]), .Y (n_30));
  CLKINVX4 g5559(.A (LED[4]), .Y (n_50));
  INVXL g5564(.A (LED[3]), .Y (n_0));
  INVXL g5561(.A (LED[1]), .Y (n_26));
  INVXL g5563(.A (LED[8]), .Y (n_46));
  CLKINVX4 g5555(.A (current_state[0]), .Y (n_14));
  INVXL g5562(.A (LED[12]), .Y (n_21));
  NAND2X6 g5608__9315(.A (reset), .B (n_36), .Y (n_42));
  CLKINVX4 fopt5613(.A (LED[6]), .Y (n_128));
  CLKINVX8 fopt5618(.A (LED[0]), .Y (n_133));
  BUFX2 drc_buf_sp5651(.A (n_110), .Y (n_183));
  BUFX2 fopt5681(.A (n_122), .Y (n_167));
  AO21X1 g2(.A0 (LED[1]), .A1 (n_110), .B0 (n_111), .Y (n_214));
  NAND2BX2 g5691(.AN (n_36), .B (reset), .Y (n_215));
  NAND4BX1 g5692(.AN (n_19), .B (n_62), .C (n_60), .D (n_65), .Y
       (n_216));
  NOR2X6 g5695(.A (n_219), .B (n_63), .Y (n_220));
  NAND3X8 g3(.A (n_60), .B (LED[4]), .C (n_76), .Y (n_219));
  NAND2X2 g5548__5697(.A (LED[3]), .B (LED[2]), .Y (n_10));
  NAND2BX1 g5699(.AN (current_index[2]), .B (n_16), .Y (n_217));
  OAI2BB1X1 g5467__5705(.A0N (n_71), .A1N (n_216), .B0 (n_84), .Y
       (n_110));
endmodule

